### ISSUE TITLE
PyMI does not build on 3.12

### ISSUE THREAD

**Issue by ader1990** [cloudbase/PyMI#48]
Error while building:

```
Utils.cpp
  PyMI\Utils.cpp(123): error C3861: 'PyUnicode_GetSize': identifier not found
  PyMI\Utils.cpp(146): error C3861: 'PyUnicode_GetSize': identifier not found
  PyMI\Utils.cpp(147): error C3536: 'len': cannot be used before it is initialized
  error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
```

**Comment by ader1990** [comment]
Fixed-By: https://github.com/cloudbase/PyMI/commit/c6a9502ea2c65116ef74d5861a067a027c6713c8
