### ISSUE TITLE
PyMI does not build on 3.13

### ISSUE THREAD

**Issue by mtnpke** [cloudbase/PyMI#53]
```
      PyMI.cpp
      PyMI\PyMI.cpp(37): error C3861: 'PyEval_ThreadsInitialized': identifier not found
      PyMI\PyMI.cpp(39): warning C4996: 'PyEval_InitThreads': deprecated in 3.9
```

PyEval_ThreadsInitialized was deprecated in 3.9 and apparently removed in 3.12

**Comment by ader1990** [comment]
Hello @mtnpke, this issue was solved by: https://github.com/cloudbase/PyMI/pull/54.

Thanks!
